
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE10_LITE_Default(



	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW

	
);

Four_bit_Full_Adder_LED_Display u0 (
						.SW(SW),
						.LEDR(LEDR));

endmodule
