
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE10_LITE_Default(



	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,
	
	
	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX5

	
);

Four_bit_Ful_Adder_7_Segment_Display_Behavioral u0 (
						.SW(SW),
						.LEDR(LEDR),
						.HEX0(HEX0),
						.HEX1(HEX1),
						.HEX3(HEX3),
						.HEX5(HEX5));

endmodule
